- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: ipv4 Addresses
      debug:
        msg: "{{ ansible_all_ipv4_addresses }}"

